before_script:
  - export PATH=$PATH:/opt/apache-maven-3.8.1/bin
build-maven-project:
  image: maven
  stage: build
  script:
  - mvn package
  artifacts:
    paths:
      - /home/gitlab-runner/
  
sonarqube_master_job:
  stage: test
  only:
    - main
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD
