stages:
  - build
  - test
  - deploy

    
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."


sonarqube_master_job:
  stage: test
  only:
    - main
  script:
    - sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD


unit-test-job:   
  stage: test    
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 5
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test    
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 5
    - echo "No lint issues found."

deploy-job:      
  stage: deploy
  script:
    - echo "Dploying application..."
    - echo "Application successfully deployed."

