image:
  name: sonarsource/sonar-scanner-cli
  entrypoint: [""]
variables:
  SONAR_LOGIN: $SONAR_LOGIN
  SONAR_URL: $SONAR_URL
  SONAR_PASSWORD: $SONAR_PASSWORD
  GIT_DEPTH: 0
sonarqube-check:
  stage: test
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - main