image:
  name:  sonarsource/sonar-scanner-cli:latest
  entrypoint: [""]
variables:
  SONAR_TOKEN: ${SONAR_LOGIN}
  SONAR_HOST_URL: ${SONAR_URL}
  GIT_DEPTH: 0
sonarqube-check:
  stage: test
  variables:
    SONAR_PROJECT_BASE_DIR: "$CI_PROJECT_DIR"
  script:
    - sonar-scanner -Dsonar.projectKey="$CI_PROJECT_NAME"
  allow_failure: false
  only:
    - branches
    - merge_requests
    - master