stages: 
    - build
    - test
build-code-job:
    stage: build
    script:
       - echo "--- build  Başarılı ---"

test-code-job:
    stage: test
    script: echo "--- Test Başarılı"

test-code-job2:
    stage: test 
    script:
        -echo "*_'_* Test 2 Başarılı" 
